# Generated by Django 4.2.18 on 2025-03-26 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/thumbnails/')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ClassroomProject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('overview_text', models.TextField(blank=True, null=True)),
                ('ppt_file', models.FileField(blank=True, null=True, upload_to='projects/sessions/')),
                ('module_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ProjectSession',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='projects/assets/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF'), ('ppt', 'PowerPoint'), ('doc', 'Document'), ('other', 'Other')], default='other', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='projects.classroomproject')),
            ],
        ),
        migrations.CreateModel(
            name='ReflectiveQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField(help_text="Store options as a dictionary, e.g. {'1': 'A', '2': 'B', '3': 'C'}")),
                ('answers', models.JSONField(help_text='Store correct answer indices as a list, e.g. [1, 3]')),
                ('multiselect', models.BooleanField(default=False, help_text='Whether multiple answers can be selected')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='projects.classroomproject')),
            ],
        ),
        migrations.AlterModelOptions(
            name='projectsubmission',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
