# Generated by Django 4.2.18 on 2025-03-28 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_classroomproject_projectsession_projectasset_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reflectivequiz',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='projectasset',
            table='ProjectAsset',
        ),
        migrations.AlterModelTable(
            name='projectsubmission',
            table='ProjectSubmission',
        ),
        migrations.CreateModel(
            name='ReflectiveQuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='projects.reflectivequiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ReflectiveQuizSubmission',
                'managed': True,
            },
        ),
    ]
