# Generated by Django 4.2.18 on 2025-02-07 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactNo', models.CharField(max_length=15)),
                ('AdditionalContactNo', models.CharField(blank=True, max_length=15, null=True)),
                ('Address', models.TextField()),
                ('Location', models.CharField(max_length=255)),
                ('Pincode', models.CharField(max_length=10)),
                ('CityCode', models.CharField(max_length=10)),
                ('StateCode', models.CharField(max_length=10)),
                ('CountryCode', models.CharField(max_length=10)),
                ('LastUsedDevice', models.CharField(blank=True, max_length=255, null=True)),
                ('PromoCode', models.CharField(blank=True, max_length=50, null=True)),
                ('PromoRefCode', models.CharField(blank=True, max_length=50, null=True)),
                ('ModifiedOn', models.DateTimeField(auto_now=True)),
                ('CustomerGST', models.CharField(blank=True, max_length=15, null=True)),
                ('UserSource', models.CharField(blank=True, max_length=100, null=True)),
                ('SchoolName', models.CharField(blank=True, max_length=255, null=True)),
                ('BoardId', models.IntegerField(blank=True, null=True)),
                ('GradeId', models.IntegerField(blank=True, null=True)),
                ('QuestId', models.IntegerField(blank=True, null=True)),
                ('LastQuestAccessed', models.DateTimeField(blank=True, null=True)),
                ('IsDirectUser', models.BooleanField(default=False)),
                ('UTMData', models.JSONField(blank=True, null=True)),
                ('AdmissionNo', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userdetails',
            },
        ),
    ]
