# Generated by Django 4.2.18 on 2025-02-07 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationId', models.IntegerField()),
                ('ModifiedOn', models.DateTimeField(auto_now=True)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('ImportCode', models.CharField(blank=True, max_length=50, null=True)),
                ('Lid', models.IntegerField(blank=True, null=True)),
                ('Gid', models.IntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usergroup',
                'unique_together': {('user', 'group', 'LocationId')},
            },
        ),
    ]
