# Generated by Django 4.2.18 on 2025-02-13 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_altphonenumber_user_firstname_user_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('LastName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('roll_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('parent_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('parent_email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('parent_phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('admission_number', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.division')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.grade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
